.TH "FIXHEADTAILS.ECLASS" "5" "Aug 2004" "Portage 2.0.51" "portage"
.SH "NAME"
fixheadtails.eclass \- functions for replacing obsolete head/tail invocations 
with newer POSIX compliant ones.
.SH "DESCRIPTION"
The \fBfixheadtails\fR eclass contains functions for parsing file(s) and 
replacing obsolete head/tail invocations in the form similar to:
.TP
head -# <file>
.TP
with the newer POSIX compliant form of:
.TP
head -n# <file>
.SH "FUNCTIONS"
\fBNOTE\fR: these functions are usually used in the \fIsrc_unpack\fR function.
.TP
.BR "ht_fix_file " "\fI<file1> [file2] [file3] [...]\fR"
Fixes head/tail invocations in specific files.
.TP
.BR "ht_fix_all"
Scans the current directory (recursively), calling \fBht_fix_file\fR for each
file that contains an obsolete head/tail invocation.
.SH "REPORTING BUGS"
Please report bugs via http://bugs.gentoo.org/
.SH "SEE ALSO"
.BR ebuild (5)
.SH "FILES"
.BR /usr/portage/eclass/fixheadtails.eclass
.SH "AUTHORS"
Aaron Walker <ka0ttic@gentoo.org>
.SH "CVS HEADER"
$Header: /var/cvsroot/gentoo-src/portage/man/fixheadtails.eclass.5,v 1.3.2.1 2005/01/15 00:19:36 vapier Exp $
