.TH "FIXPACKAGES" "1" "Dec 2011" "Portage VERSION" "Portage"
.SH NAME
fixpackages \- Perform package move updates for all packages
.SH SYNOPSIS
\fBfixpackages\fR
.SH DESCRIPTION
The fixpackages program performs package move updates on configuration
files, installed packages, and binary packages.
.SH "REPORTING BUGS"
Please report bugs via https://bugs.gentoo.org/
.SH AUTHORS
Zac Medico <zmedico@gentoo.org>
.SH "SEE ALSO"
.BR emaint (1),
.BR emerge (1)
