.TH "ETC-UPDATE" "1" "Mar 2012" "Portage VERSION" "Portage"
.SH "НАЗВАНИЕ"
etc\-update \- обработка изменений конфигурационных файлов
.SH "СИНТАКСИС"
.BR etc\-update
[\fIопции\fR] [\fI--automode <режим>\fR] [\fIпути для сканирования\fR]
.SH "ОПИСАНИЕ"
Утилиту \fIetc\-update\fR следует запускать после установки
новых пакетов для проверки предлагаемых обновлений
конфигурационных файлов. Если новый конфигурационный файл
может перезаписать имеющийся, \fIetc\-update\fR спросит
у пользователя, как с ним поступить.
.PP
\fIetc\-update\fR проверяет все каталоги, заданные в командной
строке. Если никаких путей не задано, тогда будет использована
переменная \fICONFIG_PROTECT\fR. Все конфигурационные файлы,
которые будут найдены в переменной \fICONFIG_PROTECT_MASK\fR
будут обновлены программой \fIetc\-update\fR автоматически.
Подробнее об этом смотри в справке по \fBmake.conf\fR(5).
.PP
\fIetc\-update\fR учитывает переменные \fIPORTAGE_CONFIGROOT\fR
и \fIEROOT\fR при использовании ранее означенных переменных
(\fICONFIG_PROTECT\fR и \fICONFIG_PROTECT_MASK\fR).
.SH "ОПЦИИ"
.TP
.BR \-d ", " \-\-debug
Запускает оболочку со включенным режимом отладки.
.TP
.BR \-h ", " \-\-help
Неожиданно, показывает помощь.
.TP
.BR \-p ", " \-\-preen
Автоматически применить тривиальные изменения и выйти.
.TP
.BR \-v ", " \-\-verbose
Показывать в процессе работы настройки и информацию о
важных решениях.
.TP
.BR "\-\-automode <режим>"
Выбрать один из автоматических режимов работы. Разрешенные
режимы работы это \-3, \-5, \-7, \-9. Для более подробной
информации смотри текст, выдаваемый опцией \fI\-\-help\fR.
.SH "БАГТРЕКЕР"
Об обнаруженных ошибках сообщайте на https://bugs.gentoo.org/
.SH "АВТОРЫ"
.nf
Jochem Kossen and Leo Lipelis
Karl Trygve Kalleberg <karltk@gentoo.org>
Mike Frysinger <vapier@gentoo.org>
.fi
.SH "ФАЙЛЫ"
.TP
.B /etc/etc-update.conf
Здесь хранятся настройки \fIetc-update\fR.
.SH "СМОТРИ ТАКЖЕ"
.BR dispatch-conf (1),
.BR make.conf (5)

.SH "ПЕРЕВОД"
.nf
Переводчик: Елена Гаврилова <e.vl.gavrilova@yandex.ru>
Правка и обновление: Романов Владимир <blueboar2@gmail.com>
.fi
