.TH "FIXPACKAGES" "1" "Dec 2011" "Portage VERSION" "Portage"
.SH "НАЗВАНИЕ"
fixpackages \- выполняет переносы пакетов при обновлениях
для всех пакетов
.SH "СИНТАКСИС"
\fBfixpackages\fR
.SH "ОПИСАНИЕ"
Программа fixpackages выполняет переносы пакетов при обновлениях
для конфигурационных файлов, установленных пакетов и двоичных
пакетов.
.SH "БАГТРЕКЕР"
Об обнаруженных ошибках сообщайте на https://bugs.gentoo.org/
.SH "АВТОРЫ"
Zac Medico <zmedico@gentoo.org>
.SH "СМОТРИ ТАКЖЕ"
.BR emaint (1),
.BR emerge (1)

.SH "ПЕРЕВОД"
.nf
Переводчик: Романов Владимир <blueboar2@gmail.com>
.fi
